### ISSUE TITLE
Travis CI should run all tests

### ISSUE THREAD

**Issue by drsteve** [lanl/RAM-SCB#13]
Presently the Travis CI seems to only run one test (test 3?)
All tests should actually work, and so all should be run when pull requests are sent.

**Comment by louisvernon** [comment]
Updated Travis to run all tests with 5f1e2ea1d7d0d2473d239c1817ae5545d775034a 
I won't mark this issue closed until I can confirm the tests throw a non-zero exit code on failure.

**Comment by drsteve** [comment]
So Travis is definitely running all tests, but seems to be returning from the docker run with an exit status of zero (indicating success) regardless of whether a test fails.
E.g., check the build log on Travis for build #23 (scroll right to the end). Test #3 fails (minor difference, known reason, output files for tests not updated yet), but the failure is ignored. Any ideas?

**Comment by drsteve** [comment]
This has been fixed for a while now, with all tests running and output being checked. Closing.
