### ISSUE TITLE
Incorrect dimensionality on omni flux in satellite output files

### ISSUE THREAD

**Issue by drsteve** [lanl/RAM-SCB#68]
Current virtual satellite output NetCDF files make omnidirectional flux variables that are 3D (energy, pitch angle, time), where they should be 2D as the variable is integrated over pitch angle.

The 3D array is created on line 403 of ModRamSats.f90.
It is populated as 2D on line 755 of ModRamSats.f90

@Pheosics : Am I right in thinking this is going to be as simple to fix as changing the dimensionality of the array back to 2D when it's created?

**Comment by Pheosics** [comment]
That is very strange... I don't see how it is writing the omni directional flux at all right now as there should be an error when trying write the omni directional variable.

As far as I can tell, changing line 403 from
`(/iEnDim, iPaDim, iTimeDim/), iOFluxVar)`
to
`(/iEnDim, iTimeDim/), iOFluxVar)`
Should work just fine

**Comment by drsteve** [comment]
Cheers, that what I thought. I'll make the change.
